#ifndef H_ALATAR_MASKSTILES
#define H_ALATAR_MASKSTILES

// Automatically generated by script
// May have been reformatted later

namespace alatar_updated {

enum MaskTileIDs {
  kMaskTileBlank = 32,                            // Blank
  kMaskTileWallBase = 91,                         // Wall/Floor (base)
  kMaskTileSteepStairsLeftBase = 93,              // Steep Stairs Left (base)
  kMaskTileSteepStairsRightBase = 94,             // Steep Stairs Right (base)
  kMaskTileShallowStairsLeftLeftPartBase = 95,    // Shallow Stairs Left (left part) (base)
  kMaskTileShallowStairsLeftRightPartBase = 96,   // Shallow Stairs Left (right part) (base)
  kMaskTileShallowStairsRightLeftPartBase = 97,   // Shallow Stairs Right (left part) (base)
  kMaskTileShallowStairsRightRightPartBase = 98,  // Shallow Stairs Right (right part) (base)
  kLadderTileComboLeft = 101,                     // Ladder Combo Left
  kLadderTileHorizontal = 102,                    // Ladder Horizontal Only
  kLadderTileComboRight = 103,                    // Ladder Combo Left
  kMaskTileSlideLeftBase = 122,                   // Slide Left (base)
  kMaskTileSlideRightBase = 123,                  // Slide Right (base)
  kMaskTileWall001 = 127,                         // Wall/Floor (001)
  kMaskTileWall010 = 128,                         // Wall/Floor (010)
  kMaskTileWall011 = 129,                         // Wall/Floor (011)
  kMaskTileWall100 = 130,                         // Wall/Floor (100)
  kMaskTileWall101 = 131,                         // Wall/Floor (101/111)
  kMaskTileWall110 = 132,                         // Wall/Floor (110)
  kMaskTileSteepStairsLeft1 = 133,                // Steep Stairs Left (1)
  kMaskTileSteepStairsRight1 = 134,               // Steep Stairs Right (1)
  kMaskTileShallowStairsLeftLeftPart1 = 135,      // Shallow Stairs Left (left part) (1)
  kMaskTileShallowStairsLeftRightPart1 = 136,     // Shallow Stairs Left (right part) (1)
  kMaskTileShallowStairsRightLeftPart1 = 137,     // Shallow Stairs Right (left part) (1)
  kMaskTileShallowStairsRightRightPart1 = 138,    // Shallow Stairs Right (right part) (1)
  kMaskTileSlideLeft1 = 139,                      // Slide Left (1)
  kMaskTileSlideRight1 = 140,                     // Slide Right (1)
  kLadderTileVertical = 141                       // Ladder Vertical Only
};

}  // namespace alatar_updated

#endif
