close all; clear variables; clc

xSize = 64;
pngFilename = 'tiles_and_masks.png';
txtFilename = 'maskstiles.txt';
headerFilename = 'maskstiles.h';

ySize = xSize;

masksTilesCell = cell(1,0);
namesCell = cell(1,0);
constCell = cell(1,0);

index = 0;

%---------------------------------------------------------------------------
% Wall/Floor Masks
%---------------------------------------------------------------------------
[masksTilesCell0, namesCell0, constEndCell] = wall_masks(xSize);
constBase = 'kMaskTile';

N = length(constEndCell);

masksTilesCell((1:N) + index) = masksTilesCell0;
namesCell((1:N) + index) = namesCell0;

for iN = 1:N
  tmp = sprintf('%s%s', constBase, constEndCell{iN});
  constCell{index + iN} = tmp;
endfor

index = index + N;

%---------------------------------------------------------------------------
% Ladder Tiles
%---------------------------------------------------------------------------
[masksTilesCell0, namesCell0, constEndCell] = ladders(xSize);
constBase = 'kLadderTile';

N = length(constEndCell);

masksTilesCell((1:N) + index) = masksTilesCell0;
namesCell((1:N) + index) = namesCell0;

for iN = 1:N
  tmp = sprintf('%s%s', constBase, constEndCell{iN});
  constCell{index + iN} = tmp;
endfor

index = index + N;

%---------------------------------------------------------------------------
% Output PNG file
%---------------------------------------------------------------------------
nMasksTiles = length(masksTilesCell);

data = zeros(nMasksTiles * ySize, xSize, 'uint8');

for iMaskTile = 1:nMasksTiles
  s0 = 1 + (iMaskTile - 1) * ySize;
  s1 = s0 + ySize - 1;
  data(s0:s1, :) = masksTilesCell{iMaskTile};

  fprintf(1,'%d\t%s\n', iMaskTile - 1, namesCell{iMaskTile});
end

imwrite(data, pngFilename)

%---------------------------------------------------------------------------
% Output desription file
%---------------------------------------------------------------------------

fid = fopen(txtFilename, 'w');

for iMaskTile = 1:nMasksTiles
  fprintf(fid, '%d\t%s\n', iMaskTile - 1, namesCell{iMaskTile});
endfor

fclose(fid);

%---------------------------------------------------------------------------
% Output header file
%---------------------------------------------------------------------------

fid = fopen(headerFilename, 'w');

fprintf(fid, '#ifndef H_ALATAR_MASKSTILES\n');
fprintf(fid, '#define H_ALATAR_MASKSTILES\n');

fprintf(fid, '// Automatically generated by script\n');
fprintf(fid, '// May have been reformatted later\n');

fprintf(fid, 'namespace alatar_updated {\n');

fprintf(fid, 'enum MaskTileIDs {\n');

for iMaskTile = 1:nMasksTiles
  fprintf(fid, '%s = %d', constCell{iMaskTile}, iMaskTile - 1);

  if (iMaskTile == nMasksTiles)
    fprintf(fid, ' // %s\n', namesCell{iMaskTile});
  else
    fprintf(fid, ', // %s\n', namesCell{iMaskTile});
  endif
endfor

fprintf(fid, '};\n');

fprintf(fid, '}  // namespace alatar_updated\n');

fprintf(fid, '#endif\n');

fclose(fid);

